### PR TITLE
Adds support for RPM, VSS, LOAD_PCT, ECT and VPWR

### PR DESCRIPTION
**Pull request by kikosgc**
First commit with real commands: 
- Support for **_Engine RPM_**
- Support for **_Vehicle speed_**
- Support for **_Calculated Engine Load_**
- Support for **_Engine coolant temperature_**
- Support for **_VPWR_**

Tested Engine RPM - OK and was acurate with vehicle.
Tested Speed - OK and was acurate with vehicle.
Tested [Odometer](https://github.com/kikosgc/Peugeot-2008/commit/ed6d8734782caafd84d9609aa0e2a26cb6075573) - Peugeot 2008 Phase 1 DOES NOT support Odometer reading via OBD2 

**PS 13/11/2024 - Confirmed non working commands on 2008 Phase I - BAT_SOC, BAT_SOH, ODO, ALCH_PCT, EXH_RATE, FUEL_RATE, FUEL_RATE_ALT, FLI, VFUEL_RATE, RUNTM**

CC @jverkoey

### CODE REVIEW

**Comment by jverkoey** [comment]
It looks like you're trying to override your car to run these commands even though your vehicle might be indicating it doesn't support them, is that correct?

Sidecar should be asking your vehicle which parameters it supports and then only running those that the vehicle states it supports, but if this handshake behavior isn't resulting in the right outcome for you can you send me an export of your OBD logs and I'll take a look to see where/if it might be doing something odd?

https://sidecar.clutch.engineering/help/#how-to-export-obd-scan-logs

Email the db files to support@clutch.engineering.

**Comment by kikosgc** [comment]
> It looks like you're trying to override your car to run these commands even though your vehicle might be indicating it doesn't support them, is that correct?

Not exactly, I'm manually testing which commands are working (and taking note about the ones that are reported as not supported by the app). 
The RPM, VSS, LOAD_PCT, ECT and VPWR commands are confirmed to be working (there are a few other).
Seems that the Phase I 208 & 2008 are "very basic" in terms of supported commands/PIDs. 
Phase II 208 and 2008 might have a few more supported commands since they are using a slightly different BOSCH ECU as reported in several Peugeot forums (MEVD17.4.2 vs MEVD17.4.4).

> can you send me an export of your OBD logs and I'll take a look to see where/if it might be doing something odd?

Will do! Thank you

**Comment by jverkoey** [comment]
Hmm I'll take a look at the OBD logs, but this is the essential handshake flow that Sidecar uses:

1. Sidecar asks your car for it's VIN.
2. If the car responds with a VIN, use that, otherwise use the fallback VIN if you've specified one in the Sidecar settings.
3. Sidecar asks your car to respond with the set of parameters that it supports. This involves sending a series of commands that your vehicle should respond to in order to indicate support. This essentially builds a bitmask of parameter ids we can use to talk to the car.
4. Sidecar then intersects that bitmask with the SAEJ1979 parameter set defined in https://github.com/OBDb/SAEJ1979 and shows the resulting intersection in the vehicle's parameters page.

> I'm manually testing which commands are working

With the above in mind, is Sidecar reporting that RPM, VSS, LOAD_PCT, ECT and VPWR are *not* supported by your car, and you're finding that they are in fact supported?

I'm asking this because I haven't seen a car incorrectly report the set of parameters it supports yet, but if this is happening with the Peugeot then that raises some questions about how much I can trust the SAEJ1979 handshake sequence in general.

**Comment by kikosgc** [comment]
> With the above in mind, is Sidecar reporting that RPM, VSS, LOAD_PCT, ECT and VPWR are not supported by your car, and you're finding that they are in fact supported?

No, the opposite! Sidecar is accurately detecting RPM, VSS, LOAD_PCT, ECT, and VPWR as supported by my car, and I can confirm these are indeed functioning correctly.

**Comment by jverkoey** [comment]
I see! In that case you shouldn't need to check these parameters into this repository because they're essentially shadowing the SAEJ1979 commands that are included with Sidecar by default :) The parameters that go into these vehicle-specific signalsets are typically the service 21/22 commands that are extended beyond the SAEJ1979 core standard.

**Comment by kikosgc** [comment]
Oh! I didn't know that!

**Review by Thamrrty — APPROVED** [review]

**Review by Thamrrty — COMMENTED** [review]
```suggestion
    { "hdr": "7E0", "rax": "7E8", "cmd": {"01": "0C"}, "freq": 0.25,
      "signals": [
        {"id": "2008_RPM", "path": "Engine", "fmt": { "len": 16, "max": 16383.75, "div": 4, "unit": "rpm" }, "name": "Engine RPM", "suggestedMetric": "rpm", "description": "Current vehicle RPM."}
      ]},
    { "hdr": "7E0", "rax": "7E8", "cmd": {"01": "0D"}, "freq": 0.25,
      "signals": [
        {"id": "2008_VSS", "path": "Movement", "fmt": { "len": 8, "min": 0,"max": 255, "div": 4, "unit": "kilometersPerHour" }, "name": "Vehicle speed", "suggestedMetric": "speed", "description": "Current vehicle speed."}
      ]},
    { "hdr": "7E0", "rax": "7E8", "cmd": {"01": "04"}, "freq": 0.25,
      "signals": [
        {"id": "2008_LOAD_PCT", "path": "Engine", "fmt": { "len": 8, "max": 100, "mul": 100, "div": 255, "unit": "percent" }, "name": "Calculated engine load", "description": "Represents the amount of work the engine is doing. Expected to reach 100% at wide open throttle/wide open pedal at any altitude, temperature or rpm for both naturally aspirated and boosted engines. If engine load is limited for powertrain protection e.g. engine/turbocharger protection, this value may not reach 100%. For hybrid vehicles, indicates the torque produced only by the internal combustion engine, not the torque being delivered by the entire powertrain. For electric vehicles, the meaning of this parameter is undefined."}
      ]},      
    { "hdr": "7E0", "rax": "7E8", "cmd": {"01": "05"}, "freq": 0.5,
      "signals": [
        {"id": "2008_ECT", "path": "Engine", "fmt": { "len": 8, "max": 215, "min": -40, "add": -40, "unit": "celsius" }, "name": "Engine coolant temperature", "description": "Your engine temperature must operate within a certain temperature range to operate efficiently and safely. If it runs too hot, then your engine could be permanently damaged. If it runs too cold, then your engine will use more fuel than necessary."}
      ]},
    { "hdr": "7E0", "rax": "7E8", "cmd": {"01": "42"}, "freq": 0.25,
      "signals": [
        {"id": "VPWR", "path": "Battery", "fmt": { "len": 16, "max": 65535, "div": 1000, "unit": "volts" }, "name": "Control module voltage", "description": "Power input to the OBD control module. VPWR is normally battery voltage, less any voltage drop in the circuit between the battery and the control module."}
      ]} 
    ]
```

**Pull request closed without merging**
